---

- name: Create location to deploy service
  file:
    path: "{{ monitor_cron_path }}"
    state: directory
  become: yes

- name: Copy script to the client
  copy: 
    src: "{{ script_file }}"
    dest: "{{ monitor_cron_path }}"
    mode: u+x,g+x,o+x
  become: yes

- name: Run cron script 
  at:
    command: "{{ monitor_cron_path }}/{{ hostname_ts_file }}"
    count: 1
    units: minutes
    unique: yes
  become: yes

- name: Copy monitor.service
  copy:
    src: "{{ monitor_cron_file }}"
    dest: "{{ monitor_cron_path }}"
  become: yes

- name: Reload daemon service 
  command: "systemctl daemon-reload"
  become: yes

- name: Start monitor.service
  command: "systemctl start monitor"
  become: yes

- name: Enable monitor.service at boot
  command: "systemctl enable monitor"
  become: yes

